<template>
  <div class="div-question">
    <h1>{{ title }}</h1>
    <div v-for="(item, index) in questions" :key="item.id">
      <div @click="toggleItem(item)" class="question-item">
        <span>{{ item.title }}</span>
        <i class="el-icon-arrow-right" v-show="!item.open"></i>
        <i class="el-icon-arrow-down" v-show="item.open"></i>
      </div>

      <div v-if="item.open" class="question-content">
        <span>{{ item.content }}</span>
      </div>
      <div class="div-line"></div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Questions",
  props: {},
  data() {
    return {
      title: "Your best logo maker questions",
      questions: [
        {
          id: 1,
          title: "Why choose logoaidesign.com?",
          content:
            "Yes, at this time, we only support affiliate payout via PayPal. So please make sure you have a valid PayPal account to receive payment.",
          open: false,
        },
        {
          id: 2,
          title: "Is logo design free?",
          content:
            "Yes, you can use your affiliate link for your own logo purchase. You’ll get 30% off and $20 in affiliate cash rewards for every sale you make that way.",
          open: false,
        },
        {
          id: 3,
          title: "How do I make a logo?",
          content:
            "To start, just enter your company name and industry. You can select a font style, color, and symbol for inspiration. You'll be browsing custom logos generated by our AI logo maker in the matter of seconds. Click any logo to tweak colors, fonts, layouts, symbols, and more to match your brand identity.",
          open: false,
        },
        {
          id: 4,
          title: "How much does it cost to download a logo?",
          content:
            "You can create as many affiliate accounts as you need, but each account supports only one affiliate link. If you have multiple websites or blogs that require their unique link, you can sign up for various accounts—but each account will only have one affiliate link available at a time.",
          open: false,
        },
        {
          id: 5,
          title: "Do I own my logo design?",
          content:
            "When you make a withdrawal request, payment will be sent within 2 working days of making the request. If it takes longer than that and we haven’t gotten in touch, please contact us so we can investigate what’s going on with your payment at support@logoaidesign.com",
          open: false,
        },
        {
          id: 6,
          title: "What format can I download for my new logo?",
          content:
            "When you make a withdrawal request, payment will be sent within 2 working days of making the request. If it takes longer than that and we haven’t gotten in touch, please contact us so we can investigate what’s going on with your payment at support@logoaidesign.com",
          open: false,
        },
        {
          id: 7,
          title: "Will I know the fonts and colors used in my logo?",
          content:
            "When you make a withdrawal request, payment will be sent within 2 working days of making the request. If it takes longer than that and we haven’t gotten in touch, please contact us so we can investigate what’s going on with your payment at support@logoaidesign.com",
          open: false,
        },
        {
          id: 8,
          title: "Can I edit or revise my logo once purchased?",
          content:
            "logoaidesign delivers your logo package more than a designer would, this includes a high resolution logo in JPG, PNG, and vector file, and also business card, letterhead, poster templates etc.",
          open: false,
        },
        {
          id: 9,
          title: "What if I need someone to assist me with the logo edit?",
          content:
            "When you make a withdrawal request, payment will be sent within 2 working days of making the request. If it takes longer than that and we haven’t gotten in touch, please contact us so we can investigate what’s going on with your payment at support@logoaidesign.com",
          open: false,
        },
      ],
    };
  },
  methods: {
    toggleItem(item) {
      item.open = !item.open;
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.div-question {
  max-width: 900px;
  text-align: center;
  margin: auto;
  padding: 50px;
}

.question-item {
  cursor: pointer;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px;
  line-height: 32px;
  font-size: 18px;
  font-weight: bold;
  user-select: none;
  text-align: left;
}

.div-line {
  height: 0.5px;
  background-color: #000000;
  width: 100%;
}
.question-content {
  text-align: left;
  line-height: 25px;
  font-size: 16px;
  color: #5e5e5e;
  font-weight: regular;
  padding: 10px;
  display: block;
  animation: fade-in-title 0.2s ease-in-out forwards;
}
.el-icon-arrow-right,
.el-icon-arrow-down {
  font-weight: 900;
}

@keyframes fade-in-title {
  0% {
    height: 0px;
    opacity: 0;
  }

  100% {
    height: auto;
    opacity: 1;
  }
}
@media screen and (max-width: 768px) {
  h1 {
    font-size: 20px;
  }
  .question-item {
    font-size: 16px;
  }
  .question-content {
    font-size: 12px;
  }
}
</style>
